#!/usr/bin/expect

set PW [lindex $argv 0]

set timeout 5

spawn env LANG=C /usr/bin/ssh pi@hack00.local
expect {
    "(yes/no)?" {
        send "yes\n"
        exp_continue
    }
    "password:" {
        send -- "${PW}\n"
    }
}

expect {
    "\\\$" {
        log_user 0
        send "pm2 restart lights-sensor\n"
    }
}

expect {
    -regexp "\n.*\r" {
        log_user 1
        send "exit\n"
        exit 0
    }
}